version: "3"

services:

  mariadb:
    container_name: "mariadb"
    env_file:
      - .env
    build: ${MARIADB_FOLDER}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: "wordpress"
    env_file:
      - .env
    build: ${WORDPRESS_FOLDER}
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always

  nginx:
    container_name: "nginx"
    env_file:
      - .env
    build: ${NGINX_FOLDER}
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always

networks:
  inception_network:
    name: inception_network

volumes:

  wordpress_data:
    driver: local
    driver_opts:
      device: ${VOL_DIR}/wordpress_data
      o: bind # Compartir datos entre el host y el contenedor
      type: none # No automático, se debe configurar manualmente

  mariadb_data:
    driver: local
    driver_opts:
      device: ${VOL_DIR}/mariadb_data
      o: bind # Compartir datos entre el host y el contenedor
      type: none # No automático, se debe configurar manualmente
